### PR TITLE
Use ssml from https://doi.org/10.1145/3061665, and fix typos

### LINKED ISSUE #554: Blue's scaling parameters ssml and sbig implemented incorrectly?
Blue defines `s` and `S` as:
```
s = b^floor((emin-1)/2)
S = b^ceil((emax+t-1)/2)
```
(then `ssml=1/s` and `sbig=1/S`)

Anderson modifies `ssml` a bit but seems to have a mistake/typo in `sbig` in the text and in Table I. However, the value of `sbig` in his code matches Blue's:
```
ssml = b^{-floor((emin-t)/2)}
sbig = b^{-ceil((emax-t+1)/2)}
```

Lapack has
```
!  ssml = 1/s, where s was defined in https://doi.org/10.1145/355769.355771
   real(dp), parameter :: dssml = real(radix(0._dp), dp)**( - floor( &
       (minexponent(0._dp) - 1) * 0.5_dp))
!  ssml = 1/S, where S was defined in https://doi.org/10.1145/355769.355771
   real(dp), parameter :: dsbig = real(radix(0._dp), dp)**( - ceiling( &
       (maxexponent(0._dp) - digits(0._dp) + 1) * 0.5_dp))
```
that is, `ssml` from Blue and `sbig` from Anderson.

The binary64 parameters are:
```
emin = -1021
emax = 1024
t = digits = 53
```
With these values Anderson's `ssml` and Blue's `sbig` are:
```
ssml = 2^537 = 4.4989137945431964e+161
sbig = 2^{-538} = 1.1113793747425387e-162
```
Lapack's values seem to be:
```
ssml = 2^511 = 6.703903964971299e+153 
sbig = 2^{-486} = 5.0052077379577523e-147
```

I've ported Lapack's DLASSQ and Anderson's test code to Go (https://github.com/gonum/gonum/pull/1632). With Blue's values the test passes. With Lapack's `sbig` value the test fails with what seems to be an overflow result from DLASSQ, suggesting that large values haven't been scaled down sufficiently.

Am I missing anything? Could someone check this?

### PR DESCRIPTION
**Pull request by weslleyspereira**
**Description**

Fixes #554. This PR:
1. Correct some typos in the comments of ssml and sbig in `la_constants.f90`.
2. Correct the formulas for ssml, using the ones from https://doi.org/10.1145/3061665
3. Correct the formulas for sbig, using the ones from James Blue https://doi.org/10.1145/355769.355771 __[edited]__

\* The ssml from https://doi.org/10.1145/3061665 is sufficient to scale both normalized and denormalized floating-point numbers.

### CODE REVIEW

**Review by langou — APPROVED** [review]

File: SRC/la_constants.f90 [hunk 1]
```diff
@@ -119,10 +120,11 @@ module LA_CONSTANTS
...
        (maxexponent(0._dp) - digits(0._dp) + 1) * 0.5_dp)
-!  ssml = 1/s, where s was defined in https://doi.org/10.1145/355769.355771
+!  ssml >= 1/s, where s was defined in https://doi.org/10.1145/355769.355771
+!  The correction was added in https://doi.org/10.1145/3061665 to scale denormalized numbers correctly 
    real(dp), parameter :: dssml = real(radix(0._dp), dp)**( - floor( &
-       (minexponent(0._dp) - 1) * 0.5_dp))
-!  ssml = 1/S, where S was defined in https://doi.org/10.1145/355769.355771
+       (minexponent(0._dp) - digits(0._dp)) * 0.5_dp))
+!  sbig = 1/S, where S was defined in https://doi.org/10.1145/355769.355771
    real(dp), parameter :: dsbig = real(radix(0._dp), dp)**( - ceiling( &
```
Comment (vladimir-ch) [inline SRC/la_constants.f90:128]: I'm still unsure that this formula is correct. It gives `dsbig=5.0052077379577523E-147` while the Anderson's code uses the Blue's formula which gives `1.1113793747425387E-162`. Further, some test cases in my Go port overflow with this `dsbig` value but do not with Anderson's value. It seems that the part `- digits(0._dp) + 1` should be `+ digits(0._dp) - 1` to reproduce the value from Anderson's code.

Comment (weslleyspereira) [reply SRC/la_constants.f90:128]: Right! I will fix it. Thanks again!

Comment (weslleyspereira) [reply SRC/la_constants.f90:128]: Hi @vladimir-ch. Could you please review my changes once more. I think now everything is fine. Thanks!

Comment (vladimir-ch) [reply SRC/la_constants.f90:128]: Yes, LGTM. Thanks!

**Review by vladimir-ch — APPROVED** [review]

**Review by langou — APPROVED** [review]
